import type { Hazard } from "@/types/risk";

export const HAZARDS: Hazard[] = [
  // Physical hazards
  {
    id: "working_at_height",
    code: "working_at_height",
    name: "Working at Height",
    description: "Risk of falls from height during elevated work activities",
    category: "physical",
    applicableWidgetTypes: ["roofing", "scaffolding", "hvac", "glazing", "painting", "plastering", "electrical"],
    severityGuidance: "Falls from height are a leading cause of workplace fatalities",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "falls",
    code: "falls",
    name: "Falls from Height",
    description: "Falling from elevated positions, ladders, scaffolds, or roofs",
    category: "physical",
    applicableWidgetTypes: ["roofing", "scaffolding", "hvac", "glazing"],
    severityGuidance: "Can result in fatal or life-changing injuries",
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "falling_objects",
    code: "falling_objects",
    name: "Falling Objects",
    description: "Objects falling from height onto workers below",
    category: "physical",
    applicableWidgetTypes: ["scaffolding", "demolition", "roofing", "masonry", "crane_lifting"],
    severityGuidance: "Hard hats mandatory in all areas with overhead work",
    isActive: true,
    sortOrder: 3,
  },
  {
    id: "electric_shock",
    code: "electric_shock",
    name: "Electric Shock",
    description: "Contact with live electrical conductors",
    category: "physical",
    applicableWidgetTypes: ["electrical", "hvac", "demolition"],
    severityGuidance: "Can be fatal - always isolate before work",
    isActive: true,
    sortOrder: 4,
  },
  {
    id: "arc_flash",
    code: "arc_flash",
    name: "Arc Flash",
    description: "Electrical arc flash causing burns and blast injuries",
    category: "physical",
    applicableWidgetTypes: ["electrical"],
    severityGuidance: "Severe burns and blast injuries possible",
    isActive: true,
    sortOrder: 5,
  },
  {
    id: "fire",
    code: "fire",
    name: "Fire",
    description: "Risk of fire from electrical faults, hot works, or flammable materials",
    category: "physical",
    applicableWidgetTypes: ["electrical", "plumbing", "roofing"],
    isActive: true,
    sortOrder: 6,
  },
  {
    id: "hot_works",
    code: "hot_works",
    name: "Hot Works",
    description: "Burns and fire risk from welding, cutting, and brazing",
    category: "physical",
    applicableWidgetTypes: ["plumbing", "hvac", "roofing", "demolition"],
    severityGuidance: "Hot work permit required",
    isActive: true,
    sortOrder: 7,
  },
  {
    id: "manual_handling",
    code: "manual_handling",
    name: "Manual Handling",
    description: "Injuries from lifting, carrying, pushing, or pulling loads",
    category: "ergonomic",
    applicableWidgetTypes: ["plumbing", "hvac", "carpentry", "masonry", "flooring", "glazing", "plastering", "scaffolding"],
    severityGuidance: "Assess all loads - use mechanical aids where possible",
    isActive: true,
    sortOrder: 8,
  },
  {
    id: "slips_trips",
    code: "slips_trips",
    name: "Slips, Trips & Falls",
    description: "Slips on wet/contaminated surfaces or trips over obstacles",
    category: "physical",
    applicableWidgetTypes: ["plumbing", "flooring", "painting", "plastering"],
    isActive: true,
    sortOrder: 9,
  },
  {
    id: "cuts_abrasions",
    code: "cuts_abrasions",
    name: "Cuts & Abrasions",
    description: "Cuts from sharp tools, materials, or equipment",
    category: "physical",
    applicableWidgetTypes: ["carpentry", "glazing", "roofing", "plumbing"],
    isActive: true,
    sortOrder: 10,
  },
  {
    id: "power_tools",
    code: "power_tools",
    name: "Power Tools",
    description: "Injuries from use of power tools and equipment",
    category: "physical",
    applicableWidgetTypes: ["carpentry", "demolition", "flooring"],
    isActive: true,
    sortOrder: 11,
  },
  {
    id: "noise",
    code: "noise",
    name: "Noise Exposure",
    description: "Hearing damage from excessive noise levels",
    category: "physical",
    applicableWidgetTypes: ["demolition", "carpentry", "masonry"],
    severityGuidance: "Action level 80dB, limit 87dB",
    isActive: true,
    sortOrder: 12,
  },
  {
    id: "vibration",
    code: "vibration",
    name: "Hand-Arm Vibration",
    description: "HAVS from prolonged use of vibrating tools",
    category: "physical",
    applicableWidgetTypes: ["demolition", "carpentry", "masonry"],
    isActive: true,
    sortOrder: 13,
  },
  {
    id: "struck_by",
    code: "struck_by",
    name: "Struck By",
    description: "Being struck by moving plant, vehicles, or loads",
    category: "physical",
    applicableWidgetTypes: ["crane_lifting", "demolition"],
    isActive: true,
    sortOrder: 14,
  },
  {
    id: "crush",
    code: "crush",
    name: "Crush Injuries",
    description: "Crushing injuries from plant, equipment, or materials",
    category: "physical",
    applicableWidgetTypes: ["crane_lifting", "demolition", "scaffolding"],
    isActive: true,
    sortOrder: 15,
  },
  {
    id: "structural_collapse",
    code: "structural_collapse",
    name: "Structural Collapse",
    description: "Risk of building or structure collapse during works",
    category: "physical",
    applicableWidgetTypes: ["demolition", "scaffolding"],
    severityGuidance: "Structural engineer assessment required",
    isActive: true,
    sortOrder: 16,
  },
  {
    id: "scaffold_collapse",
    code: "scaffold_collapse",
    name: "Scaffold Collapse",
    description: "Failure or collapse of scaffold structure",
    category: "physical",
    applicableWidgetTypes: ["scaffolding", "masonry"],
    isActive: true,
    sortOrder: 17,
  },
  {
    id: "overturning",
    code: "overturning",
    name: "Plant Overturning",
    description: "Cranes or plant overturning during operations",
    category: "physical",
    applicableWidgetTypes: ["crane_lifting"],
    isActive: true,
    sortOrder: 18,
  },
  {
    id: "power_lines",
    code: "power_lines",
    name: "Overhead Power Lines",
    description: "Contact with overhead electrical lines",
    category: "physical",
    applicableWidgetTypes: ["crane_lifting", "scaffolding"],
    severityGuidance: "Maintain safe distances - consult DNO",
    isActive: true,
    sortOrder: 19,
  },
  {
    id: "confined_space",
    code: "confined_space",
    name: "Confined Space",
    description: "Working in confined spaces with limited access/egress",
    category: "physical",
    applicableWidgetTypes: ["plumbing", "hvac"],
    severityGuidance: "Confined space permit required",
    isActive: true,
    sortOrder: 20,
  },
  {
    id: "weather",
    code: "weather",
    name: "Adverse Weather",
    description: "Risks from wind, rain, ice, or extreme temperatures",
    category: "environmental",
    applicableWidgetTypes: ["roofing", "scaffolding", "crane_lifting"],
    isActive: true,
    sortOrder: 21,
  },

  // Chemical hazards
  {
    id: "dust",
    code: "dust",
    name: "Dust Exposure",
    description: "Respiratory hazards from dust including silica",
    category: "chemical",
    applicableWidgetTypes: ["demolition", "carpentry", "masonry", "plastering"],
    severityGuidance: "Silica dust is carcinogenic - RPE required",
    isActive: true,
    sortOrder: 22,
  },
  {
    id: "asbestos",
    code: "asbestos",
    name: "Asbestos",
    description: "Exposure to asbestos-containing materials",
    category: "chemical",
    applicableWidgetTypes: ["asbestos", "demolition"],
    severityGuidance: "Licensed work - fatal disease risk",
    isActive: true,
    sortOrder: 23,
  },
  {
    id: "asbestos_exposure",
    code: "asbestos_exposure",
    name: "Asbestos Fibre Exposure",
    description: "Inhalation of asbestos fibres during removal works",
    category: "chemical",
    applicableWidgetTypes: ["asbestos"],
    severityGuidance: "Can cause mesothelioma and asbestosis",
    isActive: true,
    sortOrder: 24,
  },
  {
    id: "solvent_exposure",
    code: "solvent_exposure",
    name: "Solvent Exposure",
    description: "Exposure to paint solvents and chemicals",
    category: "chemical",
    applicableWidgetTypes: ["painting"],
    isActive: true,
    sortOrder: 25,
  },
  {
    id: "adhesive_exposure",
    code: "adhesive_exposure",
    name: "Adhesive/Chemical Exposure",
    description: "Exposure to adhesives and flooring chemicals",
    category: "chemical",
    applicableWidgetTypes: ["flooring"],
    isActive: true,
    sortOrder: 26,
  },
  {
    id: "refrigerant_exposure",
    code: "refrigerant_exposure",
    name: "Refrigerant Exposure",
    description: "Exposure to refrigerant gases during HVAC work",
    category: "chemical",
    applicableWidgetTypes: ["hvac"],
    isActive: true,
    sortOrder: 27,
  },
  {
    id: "contamination",
    code: "contamination",
    name: "Environmental Contamination",
    description: "Spread of hazardous materials to clean areas",
    category: "chemical",
    applicableWidgetTypes: ["asbestos"],
    isActive: true,
    sortOrder: 28,
  },

  // Biological/Health hazards
  {
    id: "respiratory",
    code: "respiratory",
    name: "Respiratory Hazards",
    description: "Inhalation of harmful dusts, fumes, or fibres",
    category: "biological",
    applicableWidgetTypes: ["asbestos", "demolition", "painting"],
    isActive: true,
    sortOrder: 29,
  },
  {
    id: "dermatitis",
    code: "dermatitis",
    name: "Dermatitis",
    description: "Skin conditions from contact with irritants",
    category: "biological",
    applicableWidgetTypes: ["painting", "plastering", "flooring"],
    isActive: true,
    sortOrder: 30,
  },
  {
    id: "knee_injuries",
    code: "knee_injuries",
    name: "Knee Injuries",
    description: "Knee injuries from prolonged kneeling",
    category: "ergonomic",
    applicableWidgetTypes: ["flooring", "plastering"],
    isActive: true,
    sortOrder: 31,
  },
];

export function getHazardByCode(code: string): Hazard | undefined {
  return HAZARDS.find((h) => h.code === code);
}

export function getHazardsForWidget(widgetCode: string): Hazard[] {
  return HAZARDS.filter((h) => h.applicableWidgetTypes.includes(widgetCode));
}

export function getHazardsByCategory(category: Hazard["category"]): Hazard[] {
  return HAZARDS.filter((h) => h.category === category);
}
