import type { Mitigation } from "@/types/risk";

export const MITIGATIONS: Mitigation[] = [
  // Elimination/Substitution
  {
    id: "eliminate_height",
    code: "eliminate_height",
    name: "Eliminate Work at Height",
    description: "Design out the need for work at height where possible",
    category: "elimination",
    applicableHazardIds: ["working_at_height", "falls"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "prefabrication",
    code: "prefabrication",
    name: "Off-site Prefabrication",
    description: "Manufacture components off-site to reduce on-site risks",
    category: "elimination",
    applicableHazardIds: ["working_at_height", "manual_handling"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 2,
  },

  // Engineering Controls
  {
    id: "edge_protection",
    code: "edge_protection",
    name: "Edge Protection",
    description: "Install edge protection to prevent falls",
    category: "engineering",
    applicableHazardIds: ["working_at_height", "falls"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 3,
  },
  {
    id: "scaffold_inspection",
    code: "scaffold_inspection",
    name: "Scaffold Inspection Regime",
    description: "Regular scaffold inspections by competent person",
    category: "engineering",
    applicableHazardIds: ["scaffold_collapse", "working_at_height"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 4,
  },
  {
    id: "access_equipment",
    code: "access_equipment",
    name: "Suitable Access Equipment",
    description: "Provide appropriate access equipment (MEWP, scaffold, tower)",
    category: "engineering",
    applicableHazardIds: ["working_at_height", "falls"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 5,
  },
  {
    id: "lifting_aids",
    code: "lifting_aids",
    name: "Mechanical Lifting Aids",
    description: "Use mechanical aids to reduce manual handling",
    category: "engineering",
    applicableHazardIds: ["manual_handling"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 6,
  },
  {
    id: "lifting_equipment",
    code: "lifting_equipment",
    name: "Lifting Equipment",
    description: "Vacuum lifters, hoists, or cranes for heavy materials",
    category: "engineering",
    applicableHazardIds: ["manual_handling"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 7,
  },
  {
    id: "isolation",
    code: "isolation",
    name: "Electrical Isolation",
    description: "Isolate electrical supplies before work commences",
    category: "engineering",
    applicableHazardIds: ["electric_shock", "arc_flash"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 8,
  },
  {
    id: "lockout_tagout",
    code: "lockout_tagout",
    name: "Lock Out Tag Out (LOTO)",
    description: "Lock out energy sources and tag to prevent re-energisation",
    category: "engineering",
    applicableHazardIds: ["electric_shock", "arc_flash"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 9,
  },
  {
    id: "exclusion_zones",
    code: "exclusion_zones",
    name: "Exclusion Zones",
    description: "Establish and maintain exclusion zones around hazardous areas",
    category: "engineering",
    applicableHazardIds: ["falling_objects", "struck_by", "crane_lifting", "demolition"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 10,
  },
  {
    id: "tool_guards",
    code: "tool_guards",
    name: "Tool Guards",
    description: "Ensure all tool guards are in place and functioning",
    category: "engineering",
    applicableHazardIds: ["power_tools", "cuts_abrasions"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 11,
  },
  {
    id: "dust_suppression",
    code: "dust_suppression",
    name: "Dust Suppression",
    description: "Water suppression and extraction for dust control",
    category: "engineering",
    applicableHazardIds: ["dust"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 12,
  },
  {
    id: "ventilation",
    code: "ventilation",
    name: "Local Exhaust Ventilation",
    description: "Provide adequate ventilation for fume/vapour extraction",
    category: "engineering",
    applicableHazardIds: ["solvent_exposure", "adhesive_exposure", "dust"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 13,
  },
  {
    id: "enclosure",
    code: "enclosure",
    name: "Enclosure/Containment",
    description: "Full enclosure of work area to contain hazardous materials",
    category: "engineering",
    applicableHazardIds: ["asbestos", "asbestos_exposure", "contamination"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 14,
  },
  {
    id: "decontamination",
    code: "decontamination",
    name: "Decontamination Unit",
    description: "Full decontamination procedures for workers",
    category: "engineering",
    applicableHazardIds: ["asbestos", "asbestos_exposure", "contamination"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 15,
  },
  {
    id: "air_monitoring",
    code: "air_monitoring",
    name: "Air Monitoring",
    description: "Continuous air monitoring during hazardous works",
    category: "engineering",
    applicableHazardIds: ["asbestos", "asbestos_exposure", "dust"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 16,
  },

  // Administrative Controls
  {
    id: "hot_work_permit",
    code: "hot_work_permit",
    name: "Hot Work Permit",
    description: "Formal hot work permit system with fire watch",
    category: "administrative",
    applicableHazardIds: ["hot_works", "fire"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 17,
  },
  {
    id: "confined_space_entry",
    code: "confined_space_entry",
    name: "Confined Space Entry Permit",
    description: "Formal confined space entry permit and procedures",
    category: "administrative",
    applicableHazardIds: ["confined_space"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 18,
  },
  {
    id: "lift_plan",
    code: "lift_plan",
    name: "Lifting Plan",
    description: "Detailed lift plan prepared by appointed person",
    category: "administrative",
    applicableHazardIds: ["struck_by", "crush", "overturning"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 19,
  },
  {
    id: "appointed_person",
    code: "appointed_person",
    name: "Appointed Person",
    description: "Competent appointed person for lifting operations",
    category: "administrative",
    applicableHazardIds: ["struck_by", "crush", "overturning"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 20,
  },
  {
    id: "slinger_signaller",
    code: "slinger_signaller",
    name: "Trained Slinger/Signaller",
    description: "Trained and competent slinger/signaller",
    category: "administrative",
    applicableHazardIds: ["struck_by", "crush"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 21,
  },
  {
    id: "licensed_contractor",
    code: "licensed_contractor",
    name: "Licensed Contractor",
    description: "Use HSE licensed contractor for asbestos work",
    category: "administrative",
    applicableHazardIds: ["asbestos", "asbestos_exposure"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 22,
  },
  {
    id: "structural_survey",
    code: "structural_survey",
    name: "Structural Survey",
    description: "Structural engineer survey before demolition",
    category: "administrative",
    applicableHazardIds: ["structural_collapse"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 23,
  },
  {
    id: "asbestos_survey",
    code: "asbestos_survey",
    name: "Asbestos Survey",
    description: "Refurbishment/demolition asbestos survey",
    category: "administrative",
    applicableHazardIds: ["asbestos"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 24,
  },
  {
    id: "manual_handling_training",
    code: "manual_handling_training",
    name: "Manual Handling Training",
    description: "Training in safe manual handling techniques",
    category: "administrative",
    applicableHazardIds: ["manual_handling"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 25,
  },
  {
    id: "cisrs_trained",
    code: "cisrs_trained",
    name: "CISRS Trained Scaffolders",
    description: "All scaffolders hold valid CISRS cards",
    category: "administrative",
    applicableHazardIds: ["scaffold_collapse", "working_at_height"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 26,
  },
  {
    id: "loading_limits",
    code: "loading_limits",
    name: "Loading Limits",
    description: "Clearly marked and enforced loading limits",
    category: "administrative",
    applicableHazardIds: ["scaffold_collapse"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 27,
  },
  {
    id: "testing",
    code: "testing",
    name: "Testing & Proving",
    description: "Test installations are dead before work",
    category: "administrative",
    applicableHazardIds: ["electric_shock"],
    effectivenessRating: "high",
    isActive: true,
    sortOrder: 28,
  },
  {
    id: "weather_monitoring",
    code: "weather_monitoring",
    name: "Weather Monitoring",
    description: "Monitor weather conditions and stop work if unsafe",
    category: "administrative",
    applicableHazardIds: ["weather"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 29,
  },
  {
    id: "housekeeping",
    code: "housekeeping",
    name: "Good Housekeeping",
    description: "Maintain clean and tidy work areas",
    category: "administrative",
    applicableHazardIds: ["slips_trips"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 30,
  },
  {
    id: "first_aid",
    code: "first_aid",
    name: "First Aid Provisions",
    description: "Adequate first aid facilities and trained first aiders",
    category: "administrative",
    applicableHazardIds: ["cuts_abrasions"],
    effectivenessRating: "low",
    isActive: true,
    sortOrder: 31,
  },

  // PPE
  {
    id: "harness",
    code: "harness",
    name: "Safety Harness",
    description: "Full body harness with appropriate lanyard",
    category: "ppe",
    applicableHazardIds: ["working_at_height", "falls"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 32,
  },
  {
    id: "ppe_electrical",
    code: "ppe_electrical",
    name: "Electrical PPE",
    description: "Arc-rated clothing, insulated gloves, face shield",
    category: "ppe",
    applicableHazardIds: ["electric_shock", "arc_flash"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 33,
  },
  {
    id: "ppe_dust",
    code: "ppe_dust",
    name: "Respiratory Protection (Dust)",
    description: "FFP3 masks or powered respirators for dust",
    category: "ppe",
    applicableHazardIds: ["dust"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 34,
  },
  {
    id: "ppe_respiratory",
    code: "ppe_respiratory",
    name: "Respiratory Protection",
    description: "Appropriate respiratory protective equipment",
    category: "ppe",
    applicableHazardIds: ["solvent_exposure", "refrigerant_exposure", "respiratory"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 35,
  },
  {
    id: "ppe_skin",
    code: "ppe_skin",
    name: "Skin Protection",
    description: "Barrier cream, gloves, and protective clothing",
    category: "ppe",
    applicableHazardIds: ["dermatitis"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 36,
  },
  {
    id: "ppe_cut_resistant",
    code: "ppe_cut_resistant",
    name: "Cut-Resistant Gloves",
    description: "Cut-resistant gloves for handling sharp materials",
    category: "ppe",
    applicableHazardIds: ["cuts_abrasions"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 37,
  },
  {
    id: "knee_pads",
    code: "knee_pads",
    name: "Knee Pads",
    description: "Suitable knee protection for kneeling work",
    category: "ppe",
    applicableHazardIds: ["knee_injuries"],
    effectivenessRating: "medium",
    isActive: true,
    sortOrder: 38,
  },
];

export function getMitigationByCode(code: string): Mitigation | undefined {
  return MITIGATIONS.find((m) => m.code === code);
}

export function getMitigationsForHazard(hazardId: string): Mitigation[] {
  return MITIGATIONS.filter((m) => m.applicableHazardIds.includes(hazardId));
}

export function getMitigationsByCategory(category: Mitigation["category"]): Mitigation[] {
  return MITIGATIONS.filter((m) => m.category === category);
}

export const MITIGATION_CATEGORY_ORDER: Mitigation["category"][] = [
  "elimination",
  "substitution",
  "engineering",
  "administrative",
  "ppe",
];

export const MITIGATION_CATEGORY_LABELS: Record<Mitigation["category"], string> = {
  elimination: "Elimination",
  substitution: "Substitution",
  engineering: "Engineering Controls",
  administrative: "Administrative Controls",
  ppe: "Personal Protective Equipment",
};
