import type { ContextualQuestion, ContractorType } from "@/types/rams";

export const CONTEXTUAL_QUESTIONS: ContextualQuestion[] = [
  // Site Conditions
  {
    id: "occupied_building",
    code: "occupied_building",
    questionText: "Is the building occupied during works?",
    questionType: "boolean",
    category: "site_conditions",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "public_interface",
    code: "public_interface",
    questionText: "Will there be interface with members of the public?",
    questionType: "boolean",
    category: "site_conditions",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "live_services",
    code: "live_services",
    questionText: "Are there live services (gas, electric, water) on site?",
    questionType: "boolean",
    category: "site_conditions",
    isRequired: true,
    triggersWidgets: ["electrical"],
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "asbestos_present",
    code: "asbestos_present",
    questionText: "Is asbestos present or suspected?",
    questionType: "select",
    options: [
      { value: "none", label: "No asbestos present" },
      { value: "surveyed_clear", label: "Surveyed - no ACMs found" },
      { value: "surveyed_present", label: "Surveyed - ACMs identified" },
      { value: "not_surveyed", label: "Not yet surveyed" },
    ],
    category: "site_conditions",
    isRequired: true,
    triggersWidgets: ["asbestos"],
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "ground_conditions",
    code: "ground_conditions",
    questionText: "What are the ground conditions?",
    questionType: "select",
    options: [
      { value: "stable", label: "Stable/firm ground" },
      { value: "soft", label: "Soft ground" },
      { value: "contaminated", label: "Potentially contaminated" },
      { value: "unknown", label: "Unknown - to be assessed" },
    ],
    category: "site_conditions",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 5,
    isActive: false, // Removed - not relevant for electrical subcontractor
  },
  {
    id: "overhead_lines",
    code: "overhead_lines",
    questionText: "Are there overhead power lines within 15m of works?",
    questionType: "boolean",
    category: "site_conditions",
    isRequired: true,
    triggersWidgets: ["crane_lifting"],
    sortOrder: 6,
    isActive: true,
  },
  {
    id: "underground_services",
    code: "underground_services",
    questionText: "Will there be excavation or ground penetration?",
    questionType: "boolean",
    category: "site_conditions",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 7,
    isActive: true,
  },
  {
    id: "confined_spaces",
    code: "confined_spaces",
    questionText: "Will work involve confined space entry?",
    questionType: "boolean",
    category: "site_conditions",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 8,
    isActive: true,
  },

  // Work Environment
  {
    id: "working_at_height",
    code: "working_at_height",
    questionText: "Will work be carried out at height (above 2m)?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: ["scaffolding"],
    sortOrder: 9,
    isActive: true,
  },
  {
    id: "height_access",
    code: "height_access",
    questionText: "What access equipment will be used for work at height?",
    questionType: "multiselect",
    options: [
      { value: "scaffold", label: "Scaffold" },
      { value: "mewp", label: "MEWP (Cherry picker)" },
      { value: "tower", label: "Mobile tower scaffold" },
      { value: "ladder", label: "Ladders (short duration)" },
      { value: "podium", label: "Podium steps" },
      { value: "none", label: "No work at height" },
    ],
    category: "work_environment",
    isRequired: false,
    triggersWidgets: ["scaffolding"],
    sortOrder: 10,
    isActive: true,
  },
  {
    id: "hot_works",
    code: "hot_works",
    questionText: "Will hot works be undertaken (welding, cutting, brazing)?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 11,
    isActive: true,
  },
  {
    id: "lifting_operations",
    code: "lifting_operations",
    questionText: "Will lifting operations be required?",
    questionType: "select",
    options: [
      { value: "none", label: "No lifting operations" },
      { value: "manual", label: "Manual handling only" },
      { value: "mechanical", label: "Mechanical lifting (forklift, telehandler)" },
      { value: "crane", label: "Crane required" },
    ],
    category: "work_environment",
    isRequired: true,
    triggersWidgets: ["crane_lifting"],
    sortOrder: 12,
    isActive: true,
  },
  {
    id: "demolition",
    code: "demolition",
    questionText: "Does the project involve demolition or structural alterations?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: ["demolition"],
    sortOrder: 13,
    isActive: true,
  },
  {
    id: "night_works",
    code: "night_works",
    questionText: "Will work be carried out during night shifts?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 14,
    isActive: true,
  },
  {
    id: "weekend_works",
    code: "weekend_works",
    questionText: "Will work be carried out at weekends?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 15,
    isActive: true,
  },
  {
    id: "noise_sensitive",
    code: "noise_sensitive",
    questionText: "Is the site in a noise-sensitive area (residential, hospital)?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 16,
    isActive: true,
  },

  // Interfaces
  {
    id: "other_contractors",
    code: "other_contractors",
    questionText: "Will there be interface with other contractors?",
    questionType: "boolean",
    category: "interfaces",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 17,
    isActive: true,
  },
  {
    id: "contractor_coordination",
    code: "contractor_coordination",
    questionText: "How will contractor interfaces be managed?",
    questionType: "select",
    options: [
      { value: "single_contractor", label: "Single contractor - no interface" },
      { value: "sequential", label: "Sequential working - different areas" },
      { value: "concurrent", label: "Concurrent working - same area" },
      { value: "coordination_required", label: "Complex interface - coordination plan required" },
    ],
    category: "interfaces",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 18,
    isActive: true,
  },
  {
    id: "client_operations",
    code: "client_operations",
    questionText: "Will the client's operations continue during works?",
    questionType: "boolean",
    category: "interfaces",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 19,
    isActive: true,
  },
  {
    id: "deliveries",
    code: "deliveries",
    questionText: "Are vehicle deliveries required to site?",
    questionType: "select",
    options: [
      { value: "none", label: "No deliveries" },
      { value: "light", label: "Light vehicles only (vans)" },
      { value: "hgv", label: "HGV deliveries required" },
      { value: "abnormal", label: "Abnormal loads" },
    ],
    category: "interfaces",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 20,
    isActive: true,
  },
  {
    id: "pedestrian_traffic",
    code: "pedestrian_traffic",
    questionText: "Will pedestrian traffic routes be affected?",
    questionType: "boolean",
    category: "interfaces",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 21,
    isActive: true,
  },
  {
    id: "vehicle_traffic",
    code: "vehicle_traffic",
    questionText: "Will vehicle traffic be affected?",
    questionType: "boolean",
    category: "interfaces",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 22,
    isActive: true,
  },

  // General
  {
    id: "permit_required",
    code: "permit_required",
    questionText: "Which permits to work are required?",
    questionType: "multiselect",
    options: [
      { value: "hot_work", label: "Hot Work Permit" },
      { value: "electrical", label: "Electrical Isolation Permit" },
      { value: "confined_space", label: "Confined Space Entry Permit" },
      { value: "excavation", label: "Excavation Permit" },
      { value: "roof_access", label: "Roof Access Permit" },
      { value: "none", label: "No permits required" },
    ],
    category: "general",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 23,
    isActive: true,
  },
  {
    id: "environmental_constraints",
    code: "environmental_constraints",
    questionText: "Are there environmental constraints (watercourse, protected species)?",
    questionType: "boolean",
    category: "general",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 24,
    isActive: true,
  },
  {
    id: "heritage_site",
    code: "heritage_site",
    questionText: "Is this a heritage/listed building?",
    questionType: "boolean",
    category: "general",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 25,
    isActive: true,
  },
  {
    id: "temporary_works",
    code: "temporary_works",
    questionText: "Are temporary works required (propping, shoring)?",
    questionType: "boolean",
    category: "general",
    isRequired: false,
    triggersWidgets: ["scaffolding"],
    sortOrder: 26,
    isActive: true,
  },
  {
    id: "fire_protection",
    code: "fire_protection",
    questionText: "Will existing fire protection systems be impaired?",
    questionType: "boolean",
    category: "general",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 27,
    isActive: true,
  },
  {
    id: "security_requirements",
    code: "security_requirements",
    questionText: "Are there special security requirements?",
    questionType: "select",
    options: [
      { value: "none", label: "Standard site security" },
      { value: "enhanced", label: "Enhanced security (vetting required)" },
      { value: "restricted", label: "Restricted access site" },
      { value: "high_security", label: "High security (MOD, government)" },
    ],
    category: "general",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 28,
    isActive: true,
  },
  {
    id: "welfare_facilities",
    code: "welfare_facilities",
    questionText: "What welfare facilities are available?",
    questionType: "multiselect",
    options: [
      { value: "existing", label: "Use existing building facilities" },
      { value: "cabins", label: "Welfare cabins to be provided" },
      { value: "portable", label: "Portable toilets only" },
      { value: "offsite", label: "Off-site facilities" },
    ],
    category: "general",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 29,
    isActive: true,
    visibleFor: ["main_contractor"], // Subcontractors use MC welfare
  },
  {
    id: "first_aid_provision",
    code: "first_aid_provision",
    questionText: "What first aid provision is required?",
    questionType: "select",
    options: [
      { value: "kit_only", label: "First aid kit only (< 5 workers)" },
      { value: "first_aider", label: "Trained first aider on site" },
      { value: "multiple", label: "Multiple first aiders required" },
    ],
    category: "general",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 30,
    isActive: true,
    visibleFor: ["main_contractor"], // Subcontractors use MC first aid
  },

  // Additional specialist questions
  {
    id: "hazardous_substances",
    code: "hazardous_substances",
    questionText: "Will hazardous substances (COSHH) be used?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 31,
    isActive: true,
  },
  {
    id: "dust_generating",
    code: "dust_generating",
    questionText: "Will works generate significant dust (including silica)?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 32,
    isActive: true,
  },
  {
    id: "manual_handling_significant",
    code: "manual_handling_significant",
    questionText: "Will significant manual handling be required?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 33,
    isActive: true,
  },
  {
    id: "lone_working",
    code: "lone_working",
    questionText: "Will any workers be working alone?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 34,
    isActive: true,
  },
  {
    id: "young_workers",
    code: "young_workers",
    questionText: "Will young workers (under 18) be on site?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 35,
    isActive: true,
  },
  {
    id: "expectant_mothers",
    code: "expectant_mothers",
    questionText: "Could expectant or new mothers be working on this project?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 36,
    isActive: false, // Removed - not relevant for electrical subcontractor
  },
  {
    id: "working_near_water",
    code: "working_near_water",
    questionText: "Will works be carried out near water (river, lake, coast)?",
    questionType: "boolean",
    category: "site_conditions",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 37,
    isActive: true,
  },
  {
    id: "railway_proximity",
    code: "railway_proximity",
    questionText: "Is the site near a railway line?",
    questionType: "boolean",
    category: "site_conditions",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 38,
    isActive: true,
  },
  {
    id: "highway_works",
    code: "highway_works",
    questionText: "Will works affect the public highway?",
    questionType: "boolean",
    category: "site_conditions",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 39,
    isActive: true,
  },
  {
    id: "fragile_surfaces",
    code: "fragile_surfaces",
    questionText: "Will work involve access to fragile surfaces (rooflight, asbestos cement)?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: ["roofing"],
    sortOrder: 40,
    isActive: true,
  },

  // Emergency & Environmental
  {
    id: "nearest_hospital",
    code: "nearest_hospital",
    questionText: "What is the nearest A&E / Hospital?",
    questionType: "text",
    category: "emergency",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 41,
    isActive: true,
  },
  {
    id: "hospital_distance",
    code: "hospital_distance",
    questionText: "Distance/travel time to nearest A&E?",
    questionType: "text",
    category: "emergency",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 42,
    isActive: true,
  },
  {
    id: "emergency_assembly",
    code: "emergency_assembly",
    questionText: "Where is the emergency assembly point?",
    questionType: "text",
    category: "emergency",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 43,
    isActive: true,
  },
  {
    id: "fire_evacuation_route",
    code: "fire_evacuation_route",
    questionText: "What is the fire evacuation route?",
    questionType: "text",
    category: "emergency",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 44,
    isActive: false, // Removed
  },
  {
    id: "site_emergency_contact",
    code: "site_emergency_contact",
    questionText: "Site emergency contact name and number?",
    questionType: "text",
    category: "emergency",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 45,
    isActive: true,
  },
  {
    id: "rescue_plan",
    code: "rescue_plan",
    questionText: "Is a specific rescue plan required (e.g., for work at height, confined space)?",
    questionType: "boolean",
    category: "emergency",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 46,
    isActive: true,
  },
  {
    id: "rescue_plan_details",
    code: "rescue_plan_details",
    questionText: "Describe the rescue plan arrangements:",
    questionType: "text",
    category: "emergency",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 47,
    isActive: true,
    dependsOn: { questionId: "rescue_plan", value: true },
    placeholder: "Describe rescue procedures, equipment available, trained personnel, communication methods, etc.",
  },

  // Environmental Procedures
  {
    id: "spill_potential",
    code: "spill_potential",
    questionText: "Is there potential for spills (oil, chemicals, fuel)?",
    questionType: "boolean",
    category: "environmental",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 47,
    isActive: true,
  },
  {
    id: "spill_kit_required",
    code: "spill_kit_required",
    questionText: "Are spill kits available on site?",
    questionType: "select",
    options: [
      { value: "not_required", label: "Not required" },
      { value: "general", label: "General purpose spill kit" },
      { value: "oil", label: "Oil-only spill kit" },
      { value: "chemical", label: "Chemical spill kit" },
      { value: "multiple", label: "Multiple types required" },
    ],
    category: "environmental",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 48,
    isActive: true,
  },
  {
    id: "dust_control_measures",
    code: "dust_control_measures",
    questionText: "What dust control measures will be implemented?",
    questionType: "multiselect",
    options: [
      { value: "none_required", label: "No significant dust" },
      { value: "water_suppression", label: "Water suppression" },
      { value: "extraction", label: "On-tool extraction" },
      { value: "screens", label: "Dust screens/sheeting" },
      { value: "damping", label: "Damping down" },
      { value: "ppe", label: "RPE for workers" },
    ],
    category: "environmental",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 49,
    isActive: true,
  },
  {
    id: "noise_control_measures",
    code: "noise_control_measures",
    questionText: "What noise control measures will be implemented?",
    questionType: "multiselect",
    options: [
      { value: "none_required", label: "No significant noise" },
      { value: "restricted_hours", label: "Restricted working hours" },
      { value: "acoustic_screens", label: "Acoustic screens/barriers" },
      { value: "silenced_equipment", label: "Silenced equipment" },
      { value: "hearing_protection", label: "Hearing protection zones" },
      { value: "neighbour_notification", label: "Neighbour notification" },
    ],
    category: "environmental",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 50,
    isActive: true,
  },
  {
    id: "waste_management",
    code: "waste_management",
    questionText: "How will waste be managed?",
    questionType: "multiselect",
    options: [
      { value: "skip", label: "Skips on site" },
      { value: "segregated", label: "Segregated waste streams" },
      { value: "hazardous", label: "Hazardous waste disposal required" },
      { value: "recycling", label: "Recycling targets" },
      { value: "swmp", label: "Site Waste Management Plan" },
    ],
    category: "environmental",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 51,
    isActive: true,
  },
  {
    id: "water_protection",
    code: "water_protection",
    questionText: "Is protection of watercourses/drains required?",
    questionType: "boolean",
    category: "environmental",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 52,
    isActive: false, // Removed
  },
  {
    id: "drain_protection",
    code: "drain_protection",
    questionText: "What drain protection measures are required?",
    questionType: "multiselect",
    options: [
      { value: "none", label: "None required" },
      { value: "covers", label: "Drain covers" },
      { value: "silt_traps", label: "Silt traps" },
      { value: "bunds", label: "Bunded storage areas" },
      { value: "settlement", label: "Settlement tanks" },
    ],
    category: "environmental",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 53,
    isActive: true,
  },
  {
    id: "vibration_sensitive",
    code: "vibration_sensitive",
    questionText: "Are there vibration-sensitive receptors nearby (buildings, equipment)?",
    questionType: "boolean",
    category: "environmental",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 54,
    isActive: true,
  },
  {
    id: "ecological_constraints",
    code: "ecological_constraints",
    questionText: "Are there ecological constraints (nesting birds, bats, protected species)?",
    questionType: "boolean",
    category: "environmental",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 55,
    isActive: true,
  },
  {
    id: "working_hours_restrictions",
    code: "working_hours_restrictions",
    questionText: "Are there restrictions on working hours?",
    questionType: "select",
    options: [
      { value: "none", label: "No restrictions" },
      { value: "standard", label: "Standard hours (07:00-19:00 Mon-Fri)" },
      { value: "restricted", label: "Restricted hours (08:00-18:00 Mon-Fri)" },
      { value: "extended", label: "Extended hours agreed" },
      { value: "custom", label: "Custom hours - specify" },
    ],
    category: "environmental",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 56,
    isActive: true,
  },

  // Lock Off Tag Off (LOTO) / Electrical Isolation
  {
    id: "electrical_isolation_required",
    code: "electrical_isolation_required",
    questionText: "Will electrical isolation be required for this work?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 30,
    isActive: true,
  },
  {
    id: "loto_procedure",
    code: "loto_procedure",
    questionText: "What Lock Off Tag Off (LOTO) procedure will be used?",
    questionType: "select",
    options: [
      { value: "company_procedure", label: "Company LOTO procedure" },
      { value: "hse_gs38", label: "HSE GS38 Safe Isolation Procedure" },
      { value: "site_specific", label: "Site-specific procedure (Main Contractor)" },
      { value: "bs7671", label: "BS 7671 Section 537 Isolation" },
    ],
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 30.1,
    isActive: true,
    dependsOn: { questionId: "electrical_isolation_required", value: true },
  },
  {
    id: "loto_equipment",
    code: "loto_equipment",
    questionText: "What Lock Off equipment will be used?",
    questionType: "multiselect",
    options: [
      { value: "mcb_lockout", label: "MCB Lockout Device" },
      { value: "mccb_lockout", label: "MCCB Lockout Device" },
      { value: "isolator_lockout", label: "Isolator Lockout Device" },
      { value: "fuse_lockout", label: "Fuse Lockout Device" },
      { value: "hasp", label: "Lockout Hasp (multi-lock)" },
      { value: "padlock", label: "Personal Safety Padlock" },
      { value: "lockout_tags", label: "Lockout Tags / Warning Notices" },
      { value: "lockout_station", label: "Lockout Station / Board" },
      { value: "plug_lockout", label: "Plug Lockout Device" },
      { value: "valve_lockout", label: "Valve Lockout (for associated services)" },
    ],
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 30.2,
    isActive: true,
    dependsOn: { questionId: "electrical_isolation_required", value: true },
    placeholder: "Select all lock off equipment to be used",
  },
  {
    id: "voltage_testing_equipment",
    code: "voltage_testing_equipment",
    questionText: "What voltage testing equipment will be used?",
    questionType: "multiselect",
    options: [
      { value: "voltage_indicator", label: "Voltage Indicator (GS38 compliant)" },
      { value: "proving_unit", label: "Proving Unit" },
      { value: "multimeter", label: "Multimeter (CAT rated)" },
      { value: "non_contact", label: "Non-Contact Voltage Detector (proximity only)" },
      { value: "test_lamps", label: "Test Lamps (2-pole)" },
      { value: "phase_rotation", label: "Phase Rotation Tester" },
    ],
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 30.3,
    isActive: true,
    dependsOn: { questionId: "electrical_isolation_required", value: true },
    placeholder: "Select voltage testing equipment (GS38 voltage indicator + proving unit required)",
  },
  {
    id: "isolation_points",
    code: "isolation_points",
    questionText: "Where are the isolation points located?",
    questionType: "text",
    category: "work_environment",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 30.4,
    isActive: true,
    dependsOn: { questionId: "electrical_isolation_required", value: true },
    placeholder: "e.g., Main switchboard Ground Floor, DB-01 in plant room",
  },
  {
    id: "multiple_energy_sources",
    code: "multiple_energy_sources",
    questionText: "Are there multiple energy sources to be isolated?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 30.5,
    isActive: true,
    dependsOn: { questionId: "electrical_isolation_required", value: true },
  },
  {
    id: "energy_sources_details",
    code: "energy_sources_details",
    questionText: "List all energy sources requiring isolation:",
    questionType: "text",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 30.6,
    isActive: true,
    dependsOn: { questionId: "multiple_energy_sources", value: true },
    placeholder: "e.g., Mains supply 400V, UPS system, Generator backup, Solar PV",
  },
  {
    id: "stored_energy",
    code: "stored_energy",
    questionText: "Is there potential for stored energy (capacitors, UPS, batteries)?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 30.7,
    isActive: true,
    dependsOn: { questionId: "electrical_isolation_required", value: true },
  },
  {
    id: "live_working",
    code: "live_working",
    questionText: "Will any live working be required?",
    questionType: "select",
    options: [
      { value: "no", label: "No - all work will be dead" },
      { value: "testing_only", label: "Live testing only (after completing work)" },
      { value: "fault_finding", label: "Live fault finding required" },
      { value: "live_work_justified", label: "Live work justified (risk assessment completed)" },
    ],
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 30.8,
    isActive: true,
    dependsOn: { questionId: "electrical_isolation_required", value: true },
  },
  {
    id: "live_work_justification",
    code: "live_work_justification",
    questionText: "Provide justification for live working:",
    questionType: "text",
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 30.9,
    isActive: true,
    dependsOn: { questionId: "live_working", value: "live_work_justified" },
    placeholder: "Explain why live working is necessary and cannot be avoided (Reg 14 EaWR 1989)",
  },
  {
    id: "reenergisation_procedure",
    code: "reenergisation_procedure",
    questionText: "What re-energisation checks will be performed?",
    questionType: "multiselect",
    options: [
      { value: "visual_inspection", label: "Visual inspection of work area" },
      { value: "tools_removed", label: "All tools and equipment removed" },
      { value: "covers_replaced", label: "All covers and guards replaced" },
      { value: "personnel_clear", label: "All personnel clear of work area" },
      { value: "warning_signs", label: "Warning signs removed" },
      { value: "testing_complete", label: "Testing/verification complete" },
      { value: "documentation", label: "Isolation certificate signed off" },
      { value: "verbal_confirmation", label: "Verbal confirmation from all workers" },
    ],
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 30.95,
    isActive: true,
    dependsOn: { questionId: "electrical_isolation_required", value: true },
    placeholder: "Select all checks to be performed before re-energisation",
  },
  {
    id: "company_loto_document",
    code: "company_loto_document",
    questionText: "Do you have a company Lock Off Tag Off procedure to include?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 30.99,
    isActive: true,
    dependsOn: { questionId: "electrical_isolation_required", value: true },
  },

  // PPE Requirements
  {
    id: "ppe_required",
    code: "ppe_required",
    questionText: "What PPE is required for this work?",
    questionType: "multiselect",
    options: [
      { value: "hard_hat", label: "Hard Hat / Safety Helmet" },
      { value: "safety_boots", label: "Safety Boots (Steel Toe)" },
      { value: "hi_vis", label: "Hi-Vis Vest / Jacket" },
      { value: "safety_glasses", label: "Safety Glasses" },
      { value: "safety_goggles", label: "Safety Goggles" },
      { value: "face_shield", label: "Face Shield" },
      { value: "gloves_general", label: "Gloves - General Purpose" },
      { value: "gloves_cut_resistant", label: "Gloves - Cut Resistant" },
      { value: "gloves_insulated", label: "Gloves - Electrically Insulated" },
      { value: "gauntlets", label: "Electrical Gauntlets" },
      { value: "insulated_sleeves", label: "Insulated Sleeves" },
      { value: "ear_defenders", label: "Ear Defenders / Plugs" },
      { value: "dust_mask", label: "Dust Mask (FFP2/FFP3)" },
      { value: "respirator", label: "Respirator" },
      { value: "overalls", label: "Overalls / Coveralls" },
      { value: "knee_pads", label: "Knee Pads" },
      { value: "harness", label: "Safety Harness (Work at Height)" },
      { value: "arc_flash_suit", label: "Arc Flash Suit" },
      { value: "arc_flash_hood", label: "Arc Flash Hood" },
    ],
    category: "work_environment",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 31,
    isActive: true,
    placeholder: "Select all PPE required for this work",
  },
  {
    id: "ppe_ceiling_work",
    code: "ppe_ceiling_work",
    questionText: "Will work be carried out in ceiling voids or confined overhead spaces?",
    questionType: "boolean",
    category: "work_environment",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 32,
    isActive: true,
  },
  {
    id: "ppe_ceiling_additional",
    code: "ppe_ceiling_additional",
    questionText: "Additional PPE for ceiling/overhead work:",
    questionType: "multiselect",
    options: [
      { value: "bump_cap", label: "Bump Cap" },
      { value: "goggles", label: "Safety Goggles (dust/debris)" },
      { value: "dust_mask", label: "Dust Mask (FFP2/FFP3)" },
      { value: "gloves", label: "Protective Gloves" },
      { value: "long_sleeves", label: "Long Sleeves" },
      { value: "knee_pads", label: "Knee Pads" },
      { value: "overalls", label: "Disposable Overalls" },
    ],
    category: "work_environment",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 33,
    isActive: true,
    dependsOn: { questionId: "ppe_ceiling_work", value: true },
  },
  {
    id: "electrical_ppe",
    code: "electrical_ppe",
    questionText: "Electrical-specific PPE required:",
    questionType: "multiselect",
    options: [
      { value: "insulated_gloves", label: "Insulated Gloves (rated voltage)" },
      { value: "leather_protectors", label: "Leather Protector Gloves" },
      { value: "insulated_sleeves", label: "Insulated Sleeves" },
      { value: "insulated_matting", label: "Insulated Matting" },
      { value: "voltage_detector", label: "Voltage Detector/Proving Unit" },
      { value: "arc_flash_ppe", label: "Arc Flash PPE (suit, hood, gloves)" },
      { value: "safety_glasses_arc", label: "Arc-Rated Safety Glasses" },
      { value: "insulated_tools", label: "Insulated Tools (1000V rated)" },
    ],
    category: "work_environment",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 34,
    isActive: true,
    placeholder: "Select electrical-specific PPE if working on or near live equipment",
  },

  // Additional Concerns
  {
    id: "additional_concerns",
    code: "additional_concerns",
    questionText: "Are there any other site-specific concerns or hazards?",
    questionType: "text",
    category: "general",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 57,
    isActive: true,
  },
  {
    id: "special_requirements",
    code: "special_requirements",
    questionText: "Are there any special client requirements or restrictions?",
    questionType: "text",
    category: "general",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 58,
    isActive: true,
  },
  {
    id: "previous_incidents",
    code: "previous_incidents",
    questionText: "Are there any known previous incidents at this location?",
    questionType: "text",
    category: "general",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 59,
    isActive: true,
  },
  {
    id: "lessons_learned",
    code: "lessons_learned",
    questionText: "Are there any lessons learned from similar projects to incorporate?",
    questionType: "text",
    category: "general",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 60,
    isActive: true,
  },

  // Subcontractor-specific questions
  {
    id: "mc_company_name",
    code: "mc_company_name",
    questionText: "Main Contractor company name?",
    questionType: "text",
    category: "interfaces",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 61,
    isActive: true,
    visibleFor: ["subcontractor"],
  },
  {
    id: "mc_site_manager",
    code: "mc_site_manager",
    questionText: "Main Contractor site manager name and contact?",
    questionType: "text",
    category: "interfaces",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 62,
    isActive: true,
    visibleFor: ["subcontractor"],
  },
  {
    id: "mc_welfare_location",
    code: "mc_welfare_location",
    questionText: "Where are the Main Contractor welfare facilities located?",
    questionType: "text",
    category: "general",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 63,
    isActive: true,
    visibleFor: ["subcontractor"],
  },
  {
    id: "mc_first_aider",
    code: "mc_first_aider",
    questionText: "Who is the Main Contractor's designated first aider?",
    questionType: "text",
    category: "emergency",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 64,
    isActive: true,
    visibleFor: ["subcontractor"],
  },
  {
    id: "mc_induction_required",
    code: "mc_induction_required",
    questionText: "Is Main Contractor site induction required before starting work?",
    questionType: "boolean",
    category: "interfaces",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 65,
    isActive: true,
    visibleFor: ["subcontractor"],
  },
  {
    id: "mc_permit_system",
    code: "mc_permit_system",
    questionText: "Does the Main Contractor operate a permit to work system?",
    questionType: "boolean",
    category: "interfaces",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 66,
    isActive: true,
    visibleFor: ["subcontractor"],
  },
  {
    id: "mc_daily_briefing",
    code: "mc_daily_briefing",
    questionText: "Are daily briefings held by the Main Contractor?",
    questionType: "boolean",
    category: "interfaces",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 67,
    isActive: true,
    visibleFor: ["subcontractor"],
  },
  {
    id: "mc_emergency_procedures",
    code: "mc_emergency_procedures",
    questionText: "Have you received the Main Contractor's emergency procedures?",
    questionType: "boolean",
    category: "emergency",
    isRequired: true,
    triggersWidgets: [],
    sortOrder: 68,
    isActive: false, // Removed
    visibleFor: ["subcontractor"],
  },
  {
    id: "designated_work_area",
    code: "designated_work_area",
    questionText: "What is your designated work area on site?",
    questionType: "text",
    category: "site_conditions",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 69,
    isActive: true,
    visibleFor: ["subcontractor"],
  },
  {
    id: "storage_area_allocated",
    code: "storage_area_allocated",
    questionText: "Has a materials/tools storage area been allocated?",
    questionType: "boolean",
    category: "site_conditions",
    isRequired: false,
    triggersWidgets: [],
    sortOrder: 70,
    isActive: true,
    visibleFor: ["subcontractor"],
  },
];

export function getQuestionByCode(code: string): ContextualQuestion | undefined {
  return CONTEXTUAL_QUESTIONS.find((q) => q.code === code);
}

export function getQuestionsByCategory(category: ContextualQuestion["category"]): ContextualQuestion[] {
  return CONTEXTUAL_QUESTIONS.filter((q) => q.category === category && q.isActive);
}

// Filter questions based on contractor type
export function getQuestionsForContractorType(
  contractorType: ContractorType
): ContextualQuestion[] {
  return CONTEXTUAL_QUESTIONS.filter((q) => {
    if (!q.isActive) return false;
    // If no visibleFor specified, show for all contractor types
    if (!q.visibleFor || q.visibleFor.length === 0) return true;
    // Otherwise, check if this contractor type is in the list
    return q.visibleFor.includes(contractorType);
  });
}

export function getQuestionsByCategoryAndContractorType(
  category: ContextualQuestion["category"],
  contractorType: ContractorType
): ContextualQuestion[] {
  return getQuestionsForContractorType(contractorType).filter(
    (q) => q.category === category
  );
}

export const QUESTION_CATEGORIES = {
  site_conditions: {
    name: "Site Conditions",
    description: "Questions about the physical site and its characteristics",
  },
  work_environment: {
    name: "Work Environment",
    description: "Questions about how and where work will be carried out",
  },
  interfaces: {
    name: "Interfaces",
    description: "Questions about interactions with others",
  },
  emergency: {
    name: "Emergency Procedures",
    description: "Emergency contacts, hospital locations, and evacuation procedures",
  },
  environmental: {
    name: "Environmental",
    description: "Dust, noise, spillage control, and environmental protection measures",
  },
  general: {
    name: "General",
    description: "General project and administrative questions",
  },
} as const;
