"use client";

import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground mb-8"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Home
        </Link>

        <div className="flex items-center gap-3 mb-6">
          <div className="h-12 w-12 rounded-xl bg-primary/20 flex items-center justify-center">
            <FileText className="h-6 w-6 text-primary" />
          </div>
          <h1 className="text-3xl font-bold">Terms of Service</h1>
        </div>

        <p className="text-muted-foreground mb-8">
          Last updated: {new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}
        </p>

        <div className="prose prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Introduction</h2>
            <p className="text-muted-foreground">
              These Terms of Service (&quot;Terms&quot;) govern your use of RAMS Builder, a Risk Assessment Method
              Statement generation service operated by Ictus Flow Ltd (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;).
              By accessing or using our service, you agree to be bound by these Terms.
            </p>
            <p className="text-muted-foreground mt-3">
              If you do not agree to these Terms, you must not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Service Description</h2>
            <p className="text-muted-foreground">
              RAMS Builder is an AI-powered tool that assists UK construction professionals in creating
              Risk Assessment Method Statements (RAMS) documents. The service uses artificial intelligence
              to generate content based on user inputs and should be used as a starting point for professional
              health and safety documentation.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Important Disclaimer - AI Generated Content</h2>
            <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 mb-4">
              <p className="text-amber-400 font-medium mb-2">Critical Notice</p>
              <p className="text-muted-foreground">
                The RAMS documents generated by this service are created using artificial intelligence and
                should be treated as drafts requiring professional review.
              </p>
            </div>
            <p className="text-muted-foreground mb-4">You acknowledge and agree that:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>
                All generated content must be reviewed, verified, and approved by a competent person
                before use on any construction project
              </li>
              <li>
                You accept full responsibility for the accuracy, completeness, and suitability of any
                RAMS document you download and use
              </li>
              <li>
                AI-generated content may contain errors, omissions, or inaccuracies that require correction
              </li>
              <li>
                Generic content must be adapted for site-specific conditions and circumstances
              </li>
              <li>
                The service does not replace professional health and safety advice
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. User Responsibilities</h2>
            <p className="text-muted-foreground mb-4">When using RAMS Builder, you agree to:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>Provide accurate and complete information when creating RAMS documents</li>
              <li>Review and verify all generated content before use</li>
              <li>Ensure a competent person signs off on all documents before implementation</li>
              <li>Comply with all applicable UK health and safety legislation including:
                <ul className="list-disc list-inside ml-6 mt-2 space-y-1">
                  <li>Health and Safety at Work etc Act 1974</li>
                  <li>Construction (Design and Management) Regulations 2015</li>
                  <li>Electricity at Work Regulations 1989</li>
                  <li>BS 7671:2018 (IET Wiring Regulations)</li>
                </ul>
              </li>
              <li>Update documents as project conditions change</li>
              <li>Brief all personnel on RAMS content before work commences</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Account Registration</h2>
            <p className="text-muted-foreground mb-4">To use RAMS Builder, you must:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>Be at least 18 years of age</li>
              <li>Provide accurate registration information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Notify us immediately of any unauthorized access</li>
              <li>Accept responsibility for all activities under your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. Subscription and Payment</h2>
            <p className="text-muted-foreground mb-4">Regarding payments and subscriptions:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>Free tier users receive 2 RAMS documents per calendar month</li>
              <li>Paid subscriptions are billed monthly or annually in advance</li>
              <li>Pay-per-use credits do not expire</li>
              <li>All prices are in GBP and inclusive of VAT where applicable</li>
              <li>Subscriptions can be cancelled at any time via account settings</li>
              <li>Refunds are available within 14 days of purchase for subscriptions</li>
              <li>Pay-per-use purchases are non-refundable once credits are used</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Intellectual Property</h2>
            <p className="text-muted-foreground">
              <strong>Our IP:</strong> The RAMS Builder platform, including its design, code, and underlying
              AI models, remains our intellectual property.
            </p>
            <p className="text-muted-foreground mt-3">
              <strong>Your Content:</strong> You retain ownership of the project information you input and
              the RAMS documents you generate. You grant us a limited license to process this data solely
              to provide the service.
            </p>
            <p className="text-muted-foreground mt-3">
              <strong>Generated Content:</strong> RAMS documents generated by the service may be used,
              modified, and distributed by you for your legitimate business purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
            <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/20 mb-4">
              <p className="text-red-400 font-medium mb-2">Important</p>
              <p className="text-muted-foreground">
                To the fullest extent permitted by law, RAMS Builder and Ictus Flow Ltd shall not be liable
                for any loss, damage, injury, or death arising from:
              </p>
            </div>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>The use or implementation of any RAMS document generated by this service</li>
              <li>Any errors, omissions, or inaccuracies in generated content</li>
              <li>Your failure to properly review and verify generated documents</li>
              <li>Your failure to comply with health and safety legislation</li>
              <li>Any indirect, consequential, or incidental damages</li>
            </ul>
            <p className="text-muted-foreground mt-4">
              Our total liability for any claims arising from the service shall not exceed the amount
              you have paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Indemnification</h2>
            <p className="text-muted-foreground">
              You agree to indemnify and hold harmless RAMS Builder, Ictus Flow Ltd, and its officers,
              directors, employees, and agents from any claims, damages, losses, or expenses (including
              legal fees) arising from:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-3">
              <li>Your use of the service</li>
              <li>Your breach of these Terms</li>
              <li>Your violation of any applicable law or regulation</li>
              <li>Your implementation of RAMS documents without proper review</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">10. Acceptable Use</h2>
            <p className="text-muted-foreground mb-4">You agree not to:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>Use the service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt the service</li>
              <li>Share your account credentials with others</li>
              <li>Use automated means to access the service without permission</li>
              <li>Reverse engineer or attempt to extract our source code</li>
              <li>Resell or redistribute generated content commercially without modification</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">11. Service Availability</h2>
            <p className="text-muted-foreground">
              We strive to provide a reliable service but do not guarantee uninterrupted availability.
              We may temporarily suspend the service for maintenance, updates, or circumstances beyond
              our control. We will provide reasonable notice of planned maintenance where possible.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">12. Termination</h2>
            <p className="text-muted-foreground mb-4">
              Either party may terminate this agreement:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>You may close your account at any time via account settings</li>
              <li>We may suspend or terminate accounts that violate these Terms</li>
              <li>Upon termination, your right to use the service ceases immediately</li>
              <li>You may export your data before account deletion</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">13. Modifications to Terms</h2>
            <p className="text-muted-foreground">
              We may modify these Terms at any time. We will notify you of material changes by email
              or through the service. Continued use after changes constitutes acceptance of the
              modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">14. Governing Law</h2>
            <p className="text-muted-foreground">
              These Terms are governed by the laws of England and Wales. Any disputes shall be subject
              to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">15. Severability</h2>
            <p className="text-muted-foreground">
              If any provision of these Terms is found to be unenforceable, the remaining provisions
              shall continue in full force and effect.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">16. Contact Information</h2>
            <p className="text-muted-foreground">
              For questions about these Terms, please contact us:
            </p>
            <div className="mt-4 p-4 rounded-xl bg-white/5">
              <p className="text-muted-foreground">
                <strong>Email:</strong> legal@ramsbuilder.com
                <br />
                <strong>Company:</strong> Ictus Flow Ltd
              </p>
            </div>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-white/10">
          <div className="flex gap-4">
            <Link href="/privacy" className="text-sm text-primary hover:underline">
              Privacy Policy
            </Link>
            <Link href="/cookies" className="text-sm text-primary hover:underline">
              Cookie Policy
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
