/**
 * Electrical Control Measures Knowledge Base
 * Extracted from HSE HSR25 (Electricity at Work Regulations 1989)
 * and INDG354 (Safety in Electrical Testing)
 *
 * Organised by Hierarchy of Controls:
 * 1. Elimination - Remove the hazard entirely
 * 2. Substitution - Replace with less hazardous alternative
 * 3. Engineering - Physical controls, guarding, isolation
 * 4. Administrative - Procedures, training, permits
 * 5. PPE - Personal protective equipment
 */

import type { ElectricalControl } from "./types";

export const ELECTRICAL_CONTROLS: ElectricalControl[] = [
  // ============================================
  // ELIMINATION CONTROLS
  // ============================================
  {
    id: "ctrl-dead-working",
    code: "dead_working",
    name: "Work on Dead Equipment Only",
    description: "Ensure all electrical equipment is made dead before any work commences - the fundamental principle of electrical safety",
    category: "elimination",
    applicableHazardCodes: [
      "electric_shock_direct",
      "electric_shock_indirect",
      "electric_burn",
      "arc_flash",
      "testing_live_parts",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 13, Reg 14",
    implementationNotes: "Live work only permitted when unreasonable to work dead (Reg 14). Must be technically impractical OR danger from making dead is greater than live work risk.",
    verificationRequired: "Prove dead with approved voltage indicator before and after use on known live source (GS38)",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "ctrl-design-out",
    code: "design_out_hazard",
    name: "Design Out Electrical Hazards",
    description: "Design electrical systems to eliminate exposure to live parts during normal operation and maintenance",
    category: "elimination",
    applicableHazardCodes: [
      "electric_shock_direct",
      "arc_flash",
      "electrical_fire",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 4(1)",
    implementationNotes: "Specify finger-safe terminals, shrouded busbars, fully insulated systems, remote racking for switchgear",
    verificationRequired: "Design review and hazard assessment",
    isActive: true,
    sortOrder: 2,
  },

  // ============================================
  // SUBSTITUTION CONTROLS
  // ============================================
  {
    id: "ctrl-reduced-voltage",
    code: "reduced_voltage",
    name: "Reduced Voltage Systems",
    description: "Use 110V centre-tapped (55V to earth) or lower voltage systems for portable equipment on construction sites",
    category: "substitution",
    applicableHazardCodes: [
      "electric_shock_direct",
      "electric_shock_indirect",
      "wet_conditions",
      "confined_space_electrical",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 6",
    implementationNotes: "BS 7671 requires 110V CTE for construction sites. Use 25V or battery tools in confined spaces with conductive surroundings.",
    verificationRequired: "Voltage verification, transformer testing",
    isActive: true,
    sortOrder: 3,
  },
  {
    id: "ctrl-battery-tools",
    code: "battery_tools",
    name: "Battery-Powered Tools",
    description: "Use cordless battery-powered tools to eliminate trailing leads and reduce shock risk",
    category: "substitution",
    applicableHazardCodes: [
      "electric_shock_direct",
      "electric_shock_indirect",
      "wet_conditions",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 6",
    implementationNotes: "Preferred for work in wet locations, confined spaces, and where trailing leads present trip hazards",
    verificationRequired: "Tool inspection, battery condition check",
    isActive: true,
    sortOrder: 4,
  },
  {
    id: "ctrl-selv-pelv",
    code: "selv_pelv",
    name: "SELV/PELV Systems",
    description: "Use Separated Extra-Low Voltage or Protected Extra-Low Voltage systems where appropriate",
    category: "substitution",
    applicableHazardCodes: [
      "electric_shock_direct",
      "confined_space_electrical",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 6, BS 7671",
    implementationNotes: "SELV transformer with no earth connection, PELV with protective earth. Max 50V AC, 120V DC ripple-free.",
    verificationRequired: "Isolation testing, source verification",
    isActive: true,
    sortOrder: 5,
  },

  // ============================================
  // ENGINEERING CONTROLS
  // ============================================
  {
    id: "ctrl-isolation",
    code: "isolation",
    name: "Safe Isolation Procedure",
    description: "Formal isolation of electrical supply using approved isolation devices with secure lockout",
    category: "engineering",
    applicableHazardCodes: [
      "electric_shock_direct",
      "electric_shock_indirect",
      "electric_burn",
      "arc_flash",
      "stored_energy",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 12, Reg 13",
    implementationNotes: "Identify circuit, isolate at suitable point, secure against reclosure, prove dead. All points of isolation secured.",
    verificationRequired: "Prove dead test using approved voltage indicator (GS38). Test indicator on known live source before AND after.",
    isActive: true,
    sortOrder: 6,
  },
  {
    id: "ctrl-lockout-tagout",
    code: "lockout_tagout",
    name: "Lock Out Tag Out (LOTO)",
    description: "Physical locking of isolation devices with personal padlocks and danger tags",
    category: "engineering",
    applicableHazardCodes: [
      "electric_shock_direct",
      "electric_shock_indirect",
      "arc_flash",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 12",
    implementationNotes: "Each worker applies own lock. Multi-lock hasps for multiple workers. Documented LOTO procedures. Key control system.",
    verificationRequired: "Lock integrity check, key register",
    isActive: true,
    sortOrder: 7,
  },
  {
    id: "ctrl-barriers-enclosures",
    code: "barriers_enclosures",
    name: "Barriers and Enclosures",
    description: "Physical barriers, insulating covers, and enclosures to prevent contact with live parts",
    category: "engineering",
    applicableHazardCodes: [
      "electric_shock_direct",
      "arc_flash",
      "testing_live_parts",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 4(4)",
    implementationNotes: "IP2X minimum for vertical surfaces, IP4X for horizontal. Insulating blankets, terminal covers, temporary enclosures for live work.",
    verificationRequired: "Barrier integrity inspection",
    isActive: true,
    sortOrder: 8,
  },
  {
    id: "ctrl-rcd-protection",
    code: "rcd_protection",
    name: "RCD Protection",
    description: "Residual Current Devices providing automatic disconnection on earth fault",
    category: "engineering",
    applicableHazardCodes: [
      "electric_shock_direct",
      "electric_shock_indirect",
      "electrical_fire",
    ],
    effectiveness: "medium",
    regulatoryReference: "EWR 1989 Reg 4(3), BS 7671",
    implementationNotes: "30mA RCDs for socket outlets and portable equipment. RCBOs preferred. Not a substitute for safe isolation.",
    verificationRequired: "RCD test button check daily, annual trip time test",
    isActive: true,
    sortOrder: 9,
  },
  {
    id: "ctrl-earthing-bonding",
    code: "earthing_bonding",
    name: "Earthing and Bonding",
    description: "Correct earthing and equipotential bonding to limit touch voltages",
    category: "engineering",
    applicableHazardCodes: [
      "electric_shock_indirect",
      "electrical_fire",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 8, BS 7671",
    implementationNotes: "Protective conductors, main bonding, supplementary bonding. Correct sizing per BS 7671.",
    verificationRequired: "Earth continuity testing, bonding verification",
    isActive: true,
    sortOrder: 10,
  },
  {
    id: "ctrl-circuit-protection",
    code: "circuit_protection",
    name: "Overcurrent Protection",
    description: "Correct sizing and type of fuses, MCBs, and MCCBs to protect against overload and short circuit",
    category: "engineering",
    applicableHazardCodes: [
      "electrical_fire",
      "electric_burn",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 5, BS 7671",
    implementationNotes: "Protection device rating must not exceed cable current-carrying capacity. Discrimination studies for fault clearance.",
    verificationRequired: "Prospective fault current measurement, Zs testing",
    isActive: true,
    sortOrder: 11,
  },
  {
    id: "ctrl-cable-protection",
    code: "cable_protection",
    name: "Cable Protection and Routing",
    description: "Physical protection of cables from mechanical damage, heat, and environmental factors",
    category: "engineering",
    applicableHazardCodes: [
      "electric_shock_indirect",
      "electrical_fire",
      "underground_cable_strike",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 7",
    implementationNotes: "Conduit, trunking, armoured cables, cable tiles and marker tape for buried cables. Avoid thermal insulation contact.",
    verificationRequired: "Visual inspection, cable depth verification",
    isActive: true,
    sortOrder: 12,
  },
  {
    id: "ctrl-exclusion-zones",
    code: "exclusion_zones",
    name: "Exclusion Zones",
    description: "Defined safe working distances from live conductors and overhead lines",
    category: "engineering",
    applicableHazardCodes: [
      "overhead_line_contact",
      "arc_flash",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 14",
    implementationNotes: "Overhead lines: 15m horizontal, 9m vertical for 400kV. Goal posts and barriers for plant. HSE GS6 guidance.",
    verificationRequired: "Survey, physical barriers, monitoring",
    isActive: true,
    sortOrder: 13,
  },
  {
    id: "ctrl-cable-avoidance",
    code: "cable_avoidance_tools",
    name: "Cable Avoidance Tools (CAT)",
    description: "Use of cable locating equipment before excavation to identify buried services",
    category: "engineering",
    applicableHazardCodes: [
      "underground_cable_strike",
    ],
    effectiveness: "medium",
    regulatoryReference: "EWR 1989 Reg 4(3)",
    implementationNotes: "CAT and Genny before any excavation. Trained operators. HSG47 procedures. Hand dig trial holes.",
    verificationRequired: "CAT calibration, operator competency",
    isActive: true,
    sortOrder: 14,
  },

  // ============================================
  // ADMINISTRATIVE CONTROLS
  // ============================================
  {
    id: "ctrl-safe-system-work",
    code: "safe_system_of_work",
    name: "Safe System of Work",
    description: "Documented safe system of work defining the method, sequence, and precautions for electrical work",
    category: "administrative",
    applicableHazardCodes: [
      "electric_shock_direct",
      "electric_shock_indirect",
      "arc_flash",
      "electrical_fire",
      "testing_live_parts",
    ],
    effectiveness: "medium",
    regulatoryReference: "EWR 1989 Reg 4(3)",
    implementationNotes: "Written procedures for all significant electrical work. Reviewed and signed by competent person. Toolbox talks.",
    verificationRequired: "Document review, worker signature",
    isActive: true,
    sortOrder: 15,
  },
  {
    id: "ctrl-permit-to-work",
    code: "permit_to_work",
    name: "Permit to Work",
    description: "Formal permit system for high-risk electrical work including HV switching and live working",
    category: "administrative",
    applicableHazardCodes: [
      "electric_shock_direct",
      "arc_flash",
      "testing_live_parts",
    ],
    effectiveness: "medium",
    regulatoryReference: "EWR 1989 Reg 4(3), Reg 14",
    implementationNotes: "Mandatory for HV work, live LV work, complex isolations. Defines work scope, hazards, precautions, time limits.",
    verificationRequired: "Permit issue and receipt signatures",
    isActive: true,
    sortOrder: 16,
  },
  {
    id: "ctrl-competent-persons",
    code: "competent_persons",
    name: "Competent Persons",
    description: "Work carried out only by persons with appropriate technical knowledge and experience",
    category: "administrative",
    applicableHazardCodes: [
      "electric_shock_direct",
      "electric_shock_indirect",
      "arc_flash",
      "electrical_fire",
      "testing_live_parts",
      "test_equipment_failure",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 16",
    implementationNotes: "Technical knowledge, experience appropriate to work. Understanding of risks. ECS/JIB card verification. Adequate supervision of trainees.",
    verificationRequired: "Qualification/card check, assessment records",
    isActive: true,
    sortOrder: 17,
  },
  {
    id: "ctrl-supervision",
    code: "supervision",
    name: "Adequate Supervision",
    description: "Appropriate level of supervision based on complexity of work and competence of workers",
    category: "administrative",
    applicableHazardCodes: [
      "electric_shock_direct",
      "arc_flash",
      "testing_live_parts",
    ],
    effectiveness: "medium",
    regulatoryReference: "EWR 1989 Reg 16",
    implementationNotes: "Direct supervision for apprentices and inexperienced workers. Periodic checks for competent workers.",
    verificationRequired: "Supervision records",
    isActive: true,
    sortOrder: 18,
  },
  {
    id: "ctrl-risk-assessment",
    code: "risk_assessment",
    name: "Electrical Risk Assessment",
    description: "Formal assessment of electrical risks before work commences",
    category: "administrative",
    applicableHazardCodes: [
      "electric_shock_direct",
      "electric_shock_indirect",
      "arc_flash",
      "electrical_fire",
      "testing_live_parts",
    ],
    effectiveness: "medium",
    regulatoryReference: "MHSWR 1999 Reg 3, EWR 1989 Reg 4",
    implementationNotes: "Identify hazards, who is at risk, evaluate risks, determine controls. Review when circumstances change.",
    verificationRequired: "Documented risk assessment",
    isActive: true,
    sortOrder: 19,
  },
  {
    id: "ctrl-test-equipment-inspection",
    code: "test_equipment_inspection",
    name: "Test Equipment Inspection",
    description: "Regular inspection and verification of test equipment condition and suitability",
    category: "administrative",
    applicableHazardCodes: [
      "test_equipment_failure",
      "testing_live_parts",
    ],
    effectiveness: "high",
    regulatoryReference: "EWR 1989 Reg 4(4)",
    implementationNotes: "GS38 compliance. Check leads, probes, fuses. CAT rating appropriate. Calibration in date. Pre-use inspection.",
    verificationRequired: "Equipment register, inspection records",
    isActive: true,
    sortOrder: 20,
  },
  {
    id: "ctrl-emergency-procedures",
    code: "emergency_procedures",
    name: "Electrical Emergency Procedures",
    description: "Documented procedures for electrical accidents including shock rescue and first aid",
    category: "administrative",
    applicableHazardCodes: [
      "electric_shock_direct",
      "electric_shock_indirect",
      "electric_burn",
      "arc_flash",
    ],
    effectiveness: "low",
    regulatoryReference: "HSWA 1974, First Aid Regulations",
    implementationNotes: "Trained first aiders, emergency isolation procedures, CPR training, emergency contact numbers posted.",
    verificationRequired: "Training records, emergency drill records",
    isActive: true,
    sortOrder: 21,
  },
  {
    id: "ctrl-maintenance-regime",
    code: "maintenance_regime",
    name: "Planned Maintenance",
    description: "Scheduled inspection, testing, and maintenance of electrical systems",
    category: "administrative",
    applicableHazardCodes: [
      "electric_shock_indirect",
      "electrical_fire",
      "arc_flash",
    ],
    effectiveness: "medium",
    regulatoryReference: "EWR 1989 Reg 4(2)",
    implementationNotes: "Periodic inspection and testing per BS 7671. Thermal imaging surveys. Connection checks. PAT testing.",
    verificationRequired: "EICR, maintenance records, PAT register",
    isActive: true,
    sortOrder: 22,
  },

  // ============================================
  // PPE CONTROLS
  // ============================================
  {
    id: "ctrl-insulating-gloves",
    code: "insulating_gloves",
    name: "Insulating Gloves",
    description: "Electrical insulating gloves rated for the voltage being worked on",
    category: "ppe",
    applicableHazardCodes: [
      "electric_shock_direct",
      "testing_live_parts",
    ],
    effectiveness: "medium",
    regulatoryReference: "EWR 1989 Reg 4(4)",
    implementationNotes: "Class rating matched to voltage. Visual inspection before each use. Leather protectors over rubber gloves. Storage in bag.",
    verificationRequired: "6-monthly dielectric test, visual inspection",
    isActive: true,
    sortOrder: 23,
  },
  {
    id: "ctrl-arc-flash-ppe",
    code: "arc_flash_ppe",
    name: "Arc Flash PPE",
    description: "Arc-rated clothing and face protection for work with arc flash risk",
    category: "ppe",
    applicableHazardCodes: [
      "arc_flash",
      "electric_burn",
    ],
    effectiveness: "medium",
    regulatoryReference: "EWR 1989 Reg 4(4)",
    implementationNotes: "Arc-rated coveralls/shirts to calculated cal/cm². Arc flash face shield. Natural fibre underlayers. No exposed skin.",
    verificationRequired: "Arc flash study to determine required rating",
    isActive: true,
    sortOrder: 24,
  },
  {
    id: "ctrl-insulated-tools",
    code: "insulated_tools",
    name: "Insulated Tools",
    description: "VDE-rated insulated hand tools for electrical work",
    category: "ppe",
    applicableHazardCodes: [
      "electric_shock_direct",
      "arc_flash",
    ],
    effectiveness: "medium",
    regulatoryReference: "EWR 1989 Reg 4(4)",
    implementationNotes: "1000V rated to IEC 60900/BS EN 60900. Double insulation. No damaged or contaminated tools. Tool inspection.",
    verificationRequired: "Visual inspection, insulation integrity",
    isActive: true,
    sortOrder: 25,
  },
  {
    id: "ctrl-safety-footwear",
    code: "safety_footwear",
    name: "Electrical Safety Footwear",
    description: "Footwear providing protection against electrical hazards",
    category: "ppe",
    applicableHazardCodes: [
      "electric_shock_direct",
      "electric_shock_indirect",
    ],
    effectiveness: "low",
    regulatoryReference: "EWR 1989 Reg 4(4)",
    implementationNotes: "ESD rated or insulating boots depending on application. Check sole condition.",
    verificationRequired: "Visual inspection",
    isActive: true,
    sortOrder: 26,
  },
  {
    id: "ctrl-test-equipment-gs38",
    code: "test_equipment_gs38",
    name: "GS38 Compliant Test Equipment",
    description: "Test probes and leads meeting HSE GS38 requirements for safe electrical testing",
    category: "ppe",
    applicableHazardCodes: [
      "test_equipment_failure",
      "testing_live_parts",
      "electric_shock_direct",
    ],
    effectiveness: "high",
    regulatoryReference: "HSE GS38",
    implementationNotes: "Fused leads (500mA HRC fuses). Finger barrier probes with max 2-4mm exposed tip. Shrouded connectors. Correct CAT rating.",
    verificationRequired: "Pre-use check of leads, probes, fuses",
    isActive: true,
    sortOrder: 27,
  },
];

export function getControlByCode(code: string): ElectricalControl | undefined {
  return ELECTRICAL_CONTROLS.find((c) => c.code === code);
}

export function getControlsByCategory(category: ElectricalControl["category"]): ElectricalControl[] {
  return ELECTRICAL_CONTROLS.filter((c) => c.category === category);
}

export function getControlsForHazard(hazardCode: string): ElectricalControl[] {
  return ELECTRICAL_CONTROLS.filter((c) => c.applicableHazardCodes.includes(hazardCode));
}

export function getActiveControls(): ElectricalControl[] {
  return ELECTRICAL_CONTROLS.filter((c) => c.isActive);
}
