/**
 * Electrical Hazards Knowledge Base
 * Extracted from HSE HSR25 (Electricity at Work Regulations 1989)
 * and INDG354 (Safety in Electrical Testing)
 */

import type { ElectricalHazard } from "./types";

export const ELECTRICAL_HAZARDS: ElectricalHazard[] = [
  // Primary Electrical Hazards - From HSR25 Regulation 3
  {
    id: "elec-shock-direct",
    code: "electric_shock_direct",
    name: "Electric Shock - Direct Contact",
    description: "Electric shock from direct contact with live conductors or exposed live parts of electrical equipment",
    category: "shock",
    severity: "critical",
    regulatoryReference: "EWR 1989 Reg 4(4), Reg 14",
    hseGuidance: "HSR25 Para 34-41",
    riskFactors: [
      "Voltage level (>50V AC, >120V DC ripple-free)",
      "Current path through body",
      "Duration of contact",
      "Environmental conditions (wet, damp)",
      "Body resistance reduced by moisture",
      "Heart condition of individual",
    ],
    atRiskPersons: [
      "Electrical workers",
      "Electricians",
      "Apprentices",
      "Maintenance personnel",
      "Other trades working near electrical equipment",
    ],
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "elec-shock-indirect",
    code: "electric_shock_indirect",
    name: "Electric Shock - Indirect Contact",
    description: "Electric shock from contact with exposed conductive parts that have become live due to insulation failure",
    category: "shock",
    severity: "high",
    regulatoryReference: "EWR 1989 Reg 4(4)",
    hseGuidance: "HSR25 Para 34-41",
    riskFactors: [
      "Faulty insulation on equipment",
      "Damage to cables or enclosures",
      "Incorrect earthing arrangements",
      "RCD protection absent or faulty",
      "Metalwork not bonded",
    ],
    atRiskPersons: [
      "All site personnel",
      "Building occupants",
      "Maintenance personnel",
      "Cleaners",
    ],
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "elec-burn",
    code: "electric_burn",
    name: "Electric Burn",
    description: "Burns caused by electrical current passing through body tissue or from contact with hot surfaces heated by electrical faults",
    category: "burn",
    severity: "high",
    regulatoryReference: "EWR 1989 Reg 4(4)",
    hseGuidance: "HSR25 Para 34",
    riskFactors: [
      "High fault currents",
      "Sustained contact with live parts",
      "Inadequate protection against faults",
      "Overloaded circuits generating heat",
    ],
    atRiskPersons: [
      "Electrical workers",
      "Personnel in proximity to electrical equipment",
    ],
    isActive: true,
    sortOrder: 3,
  },
  {
    id: "arc-flash",
    code: "arc_flash",
    name: "Arc Flash",
    description: "Explosive release of energy caused by an electric arc between conductors, producing intense heat, light, and pressure wave",
    category: "arc",
    severity: "critical",
    regulatoryReference: "EWR 1989 Reg 4(4), Reg 14",
    hseGuidance: "HSR25 Para 34, INDG354",
    riskFactors: [
      "High available fault current",
      "Working on or near live HV equipment",
      "Loose connections",
      "Contamination (dust, moisture)",
      "Incorrect tools or procedures",
      "Inadequate PPE",
    ],
    atRiskPersons: [
      "Electrical workers performing live work",
      "Personnel near switchgear",
      "Anyone in arc flash boundary",
    ],
    isActive: true,
    sortOrder: 4,
  },
  {
    id: "electrical-fire",
    code: "electrical_fire",
    name: "Fire of Electrical Origin",
    description: "Fire initiated by electrical faults, overloading, arcing, or sparks igniting nearby combustible materials",
    category: "fire",
    severity: "high",
    regulatoryReference: "EWR 1989 Reg 4(1), Reg 5",
    hseGuidance: "HSR25 Para 42-47",
    riskFactors: [
      "Overloaded cables or circuits",
      "Poor connections causing resistance heating",
      "Cables in thermal insulation",
      "Combustible materials near electrical equipment",
      "Damaged insulation",
      "Inappropriate fuse ratings",
    ],
    atRiskPersons: [
      "All building occupants",
      "Site personnel",
      "Emergency responders",
    ],
    isActive: true,
    sortOrder: 5,
  },
  {
    id: "electrical-explosion",
    code: "electrical_explosion",
    name: "Electrical Explosion",
    description: "Explosion caused by electrical arcing or sparks in flammable or explosive atmospheres",
    category: "explosion",
    severity: "critical",
    regulatoryReference: "EWR 1989 Reg 6",
    hseGuidance: "HSR25 Para 48-54",
    riskFactors: [
      "Presence of flammable gases, vapours, or dusts",
      "Non-Ex rated equipment in hazardous areas",
      "Incorrect equipment selection for zone",
      "Damaged explosion-proof enclosures",
      "Hot surfaces in explosive atmosphere",
    ],
    atRiskPersons: [
      "All personnel in hazardous area",
      "Electrical workers",
      "Process operators",
    ],
    isActive: true,
    sortOrder: 6,
  },

  // Secondary/Consequential Hazards
  {
    id: "falls-from-shock",
    code: "falls_from_shock",
    name: "Falls from Electric Shock",
    description: "Falls from height or into machinery caused by muscle contractions or startle response from electric shock",
    category: "secondary",
    severity: "high",
    regulatoryReference: "EWR 1989 Reg 4(4)",
    hseGuidance: "HSR25 Para 34",
    riskFactors: [
      "Working at height near live equipment",
      "Working near moving machinery",
      "Working near water or excavations",
      "Non-fatal shock causing loss of control",
    ],
    atRiskPersons: [
      "Electrical workers at height",
      "Workers on scaffolds or ladders",
      "Personnel near hazardous areas",
    ],
    isActive: true,
    sortOrder: 7,
  },
  {
    id: "underground-cable-strike",
    code: "underground_cable_strike",
    name: "Underground Cable Strike",
    description: "Contact with buried electrical cables during excavation or ground works causing shock, burns, or explosion",
    category: "shock",
    severity: "critical",
    regulatoryReference: "EWR 1989 Reg 4(3)",
    hseGuidance: "HSG47 Avoiding Danger from Underground Services",
    riskFactors: [
      "Inadequate cable location survey",
      "Inaccurate utility records",
      "Mechanical excavation in cable vicinity",
      "Hand digging with metal tools",
      "Damaged or unmarked cables",
    ],
    atRiskPersons: [
      "Excavator operators",
      "Groundworkers",
      "Anyone in excavation area",
    ],
    isActive: true,
    sortOrder: 8,
  },
  {
    id: "overhead-line-contact",
    code: "overhead_line_contact",
    name: "Overhead Line Contact",
    description: "Contact with or approach to overhead power lines by plant, equipment, or personnel",
    category: "shock",
    severity: "critical",
    regulatoryReference: "EWR 1989 Reg 14",
    hseGuidance: "GS6 Avoiding Danger from Overhead Power Lines",
    riskFactors: [
      "Cranes, MEWPs, or tippers near power lines",
      "Tipper vehicles with raised bodies",
      "Scaffolding erected near lines",
      "Long materials (ladders, pipes) carried vertically",
      "Inadequate exclusion zones",
    ],
    atRiskPersons: [
      "Crane operators",
      "MEWP operators",
      "Scaffolders",
      "All personnel in work area",
    ],
    isActive: true,
    sortOrder: 9,
  },

  // Testing-Specific Hazards - From INDG354
  {
    id: "testing-live-parts",
    code: "testing_live_parts",
    name: "Contact with Live Parts During Testing",
    description: "Electric shock from exposed live parts during electrical testing procedures",
    category: "shock",
    severity: "high",
    regulatoryReference: "EWR 1989 Reg 14, Reg 4(3)",
    hseGuidance: "INDG354 Section 2",
    riskFactors: [
      "Testing requiring access to live parts",
      "Exposed terminals during insulation testing",
      "High voltage applied during testing",
      "Test equipment faults",
      "Inadequate barriers or guarding",
    ],
    atRiskPersons: [
      "Electrical testers",
      "Electricians",
      "Others in test area",
    ],
    isActive: true,
    sortOrder: 10,
  },
  {
    id: "stored-energy",
    code: "stored_energy",
    name: "Stored Electrical Energy",
    description: "Shock or burn from capacitors or other components retaining electrical charge after isolation",
    category: "shock",
    severity: "high",
    regulatoryReference: "EWR 1989 Reg 13",
    hseGuidance: "HSR25 Para 107-111",
    riskFactors: [
      "Capacitors in power factor correction",
      "UPS systems and batteries",
      "Variable speed drives",
      "Cables with capacitive charge",
      "Failure to discharge before work",
    ],
    atRiskPersons: [
      "Electrical workers",
      "Maintenance personnel",
    ],
    isActive: true,
    sortOrder: 11,
  },
  {
    id: "test-equipment-failure",
    code: "test_equipment_failure",
    name: "Test Equipment Failure",
    description: "Hazards arising from faulty, damaged, or incorrectly rated test equipment",
    category: "shock",
    severity: "medium",
    regulatoryReference: "EWR 1989 Reg 4(4)",
    hseGuidance: "INDG354 Section 4, GS38",
    riskFactors: [
      "Damaged test leads or probes",
      "Incorrect CAT rating for installation",
      "Uninspected or uncalibrated equipment",
      "Fused test leads not fitted or wrong rating",
      "Barrier fingers on probes worn or missing",
    ],
    atRiskPersons: [
      "Electrical testers",
      "Electricians",
    ],
    isActive: true,
    sortOrder: 12,
  },

  // Working Environment Hazards
  {
    id: "wet-conditions",
    code: "wet_conditions",
    name: "Electrical Work in Wet Conditions",
    description: "Increased shock risk when working with electricity in wet or damp environments",
    category: "shock",
    severity: "high",
    regulatoryReference: "EWR 1989 Reg 6",
    hseGuidance: "HSR25 Para 48-54",
    riskFactors: [
      "Reduced body resistance when wet",
      "Water ingress to equipment",
      "Outdoor work in rain",
      "Condensation on equipment",
      "Flooded cable routes",
    ],
    atRiskPersons: [
      "Electrical workers",
      "All personnel in wet areas",
    ],
    isActive: true,
    sortOrder: 13,
  },
  {
    id: "confined-space-electrical",
    code: "confined_space_electrical",
    name: "Electrical Work in Confined Spaces",
    description: "Heightened electrical risks when working in confined spaces with conductive surroundings",
    category: "shock",
    severity: "high",
    regulatoryReference: "EWR 1989 Reg 6, Reg 14",
    hseGuidance: "HSR25 Para 48-54",
    riskFactors: [
      "Conductive enclosures (tanks, vessels)",
      "Reduced voltage not used (110V or lower)",
      "Limited escape routes",
      "Humid conditions",
      "Contact with earthed metalwork unavoidable",
    ],
    atRiskPersons: [
      "Electrical workers in confined spaces",
      "Welders in vessels",
      "Maintenance workers",
    ],
    isActive: true,
    sortOrder: 14,
  },
];

export function getHazardByCode(code: string): ElectricalHazard | undefined {
  return ELECTRICAL_HAZARDS.find((h) => h.code === code);
}

export function getHazardsByCategory(category: ElectricalHazard["category"]): ElectricalHazard[] {
  return ELECTRICAL_HAZARDS.filter((h) => h.category === category);
}

export function getActiveHazards(): ElectricalHazard[] {
  return ELECTRICAL_HAZARDS.filter((h) => h.isActive);
}
